export const FIELD = {
  contractName: 'contractName',
  commodityCode: 'commodityCode',

  contractCode: 'contractCode',
  openPositions: 'openPositions',
  bidQty: 'bidQty',
  bidPrice: 'bidPrice',
  pendingBuy: 'pendingBuy',
  offerPrice: 'offerPrice',
  offerQty: 'offerQty',
  pendingSell: 'pendingSell',
  filledPrice: 'filledPrice',
  filledQty: 'filledQty',
  change: 'change',
  percentageChange: 'percentageChange',
  openPrice: 'openPrice',
  highestPrice: 'highestPrice',
  lowestPrice: 'lowestPrice',
  closePrice: 'closePrice',
  prevClosePrice: 'prevClosePrice',
  settlePrice: 'settlePrice',
  tickSize: 'tickSize',
  contractPrice: 'contractPrice',
  volume: 'volume',
  lastUpdateDatetime: 'lastUpdateDatetime',
  }